import type { NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";



const AdminPage: NextPage = () => {

    const helpRequestsQuery = api.helpRequest.getHelpRequests.useQuery();
    const handleHelpRequestClicked = () => { };

    return (
        <>
            <Head>
                <title>Admin Panel</title>

                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/n.png" />
            </Head>
            <main className="container rounded-md mx-auto flex min-h-screen flex-col p-4">

                <h1 className=" text-5xl font-bold leading-normal text-blue-700 md:text-[5rem]">
                    Admin  <span className="text-purple-300 font-bold "> Panel</span>
                </h1>
                <section className="flex font-bold text-blue-500">
                    <div className="flex p-1 space-x-5 underline align-text-bottom ">
                        {helpRequestsQuery.data?.map((helpRequest) => (

                            <button onClick={handleHelpRequestClicked} key={helpRequest.id}>
                                {helpRequest.id}
                            </button>
                        ))};
                    </div>
                    {/*
                    <div>
                        <ul>
                            {messages.map(({ message, id, sender }) => (
                                <li
                                    className={`mb-2 rounded p-1 ${sender === senderID ? 'bg-gray-150' : 'bg-blue-200'
                                        }`}

                                    key={id}>{message}</li>
                            ))}
                        </ul>
                        <form className="flex">
                            <input className="rounded-md relative bottom w-full border border-black p-1 px-2"></input>

                            <button className="rounded-md bottom-40 right-12 cursor-pointer bg-blue-400 p-1 px-3 text-white hover:bg-blue-500">
                                Send
                            </button>

                        </form>
                    </div>
                                    */}

                </section>

            </main>
        </>
    );
};
export default AdminPage;
