import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";
import { HelpWidget } from "../components/HelpWidget";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Chat Ninja</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/n.png" />
      </Head>
      <main className="container rounded-md mx-auto flex min-h-screen flex-col items-center justify-center p-4">

        <h1 className=" text-5xl font-bold leading-normal text-blue-700 md:text-[5rem]">
          Chat <span className="text-purple-300 "> Ninja</span>
        </h1>
        <HelpWidget />
      </main>
    </>
  )
}
export default Home;
